### ISSUE TITLE
Add "Lint Commit Messages" Workflow

### ISSUE THREAD

**Issue by Nishitbaria** [UBA-GCOEN/StichHub#532]
**Description:**
Currently, we don't have a workflow to lint commit messages in our repository. Linting commit messages is essential for maintaining a clean and consistent commit history, making it easier for contributors and maintainers to understand the changes introduced by each commit. To address this, we propose adding a new workflow named "Lint Commit Messages."

**Workflow YAML:**
```yaml
name: Lint Commit Messages

on:
  pull_request:
  push:
    branches:
      - main  # Modify this to match the default branch name if different

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
```

**Workflow Purpose:**
The "Lint Commit Messages" workflow will be triggered on every pull request and push to the repository. It will use the `commitlint-github-action` to automatically lint commit messages and ensure they adhere to our commit message guidelines.

**Expected Behavior:**
- When a pull request is opened or updated, the workflow will be triggered to lint the commit messages in the pull request branch.
- When code is pushed directly to the repository's default branch (usually `main`), the workflow will be triggered to lint the commit messages in the pushed commits.

**Commit Message Guidelines:**
To ensure consistency and clarity in our commit messages, please follow the guidelines outlined in our CONTRIBUTING.md document.

**Note:**
Please make sure to have the `commitlint-github-action` properly configured in the repository or specify the correct version tag (`v4` in this case) for the action. Additionally, modify the `branches` section in the `on` block to match your default branch name if it's different from `main`. Once this workflow is implemented, it will help maintain high-quality commit messages in our repository.
